name: Main
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Gradle Test
        run: ./gradlew test
      - name: Gradle TestCoverageVerification
        run: ./gradlew jacocoTestCoverageVerification
      - name: Gradle Build
        run: ./gradlew build
