name: Main
on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17.0.2
      - name: Gradle Build
        run: ./gradlew build
      - name: Gradle Test
        run: ./gradlew test
      - name: Gradle TestCoverageVerification
        run: ./gradlew jacocoTestCoverageVerification
   
